### PR TITLE
Add pagination

### PR DESCRIPTION
**Pull request by mikew**
I noticed the `all` functions wouldn't actually list all of a resource.

### CODE REVIEW

**Comment by jdalrymple** [comment]
Lol I was just implementing this!

**Comment by jdalrymple** [comment]
I'll look over this in the next couple days, looks good though :)

**Comment by jdalrymple** [comment]
Just pushed my implementation, noticed it can cause problems  if there are many results.  maybe i should add some timeout option?

**Comment by mikew** [comment]
Hmm yeah, a timeout would help. Would another option for max number of pages make sense?

**Comment by jdalrymple** [comment]
What would be the use case of max number of pages? Wouldn't you want to leave that up to the user of the library? If they only wanted 2 pages, wouldn't they just pass in the per_page and page options? Hmm, I guess it would become tedious. 

Im not sure whats the best way to handle both functionalities. :confused:

**Comment by jdalrymple** [comment]
What about no time out, just include limit ( which limits the amount of results not pages)

**Comment by jdalrymple** [comment]
Alright, for now ill just add a limit argument, which will limit the amount of total results. If it still causes problems we could always add a timeout of some sort

**Comment by jdalrymple** [comment]
Added pagination in the latest release, tell me if it works for you !

**Pull request closed without merging**
