### PR TITLE
Add some Jobs related endpoint support

### PR DESCRIPTION
**Pull request by yonguelink**
Here I am again, with what is basically the same PR, but from my organisation 😀 At risk of repeating myself:

We needed a few endpoint support related to Jobs, supposed we should add them to the project.

Add support for :

1. Listing the job from a specific pipeline via `Pipelines.showJobs` AND `Jobs.showPipelineJobs`
1. Download the content from a specific file from the artifacts of a specific job via `Jobs.downloadSingleArtifactFile` 
    * Also added a way to download this single file using streams via `Jobs.downloadSingleArtifactFileStream`
1. Playing a specific job via `Jobs.play`

I tested manually, they're working (all in our project internally, we're using this right now in production).

For the stream part of the download, I saw that the regular `get` method was doing lots of work behind the scenes, and I'm not sure exactly what was really important into it...

References:

* https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-jobs
* https://docs.gitlab.com/ee/api/jobs.html#download-a-single-artifact-file
* https://docs.gitlab.com/ee/api/jobs.html#play-a-job

### CODE REVIEW

**Comment by jdalrymple** [comment]
I made a small change that moved the request library to the RequestHelper and made the stream an option on the Jobs.downloadArtifactFile. Do you know if this will still work with the XMLHttpRequest option set to true?

**Comment by jdalrymple** [comment]
I pushed the modifications in the #77-modifications branch if you wanna give it a look!

**Comment by yonguelink** [comment]
I applied your changes to my branch.

and I do not know if it'll work with the XMLHttpRequest set to true ... :( I'll try to get some time today to test it.

**Comment by yonguelink** [comment]
Sorry! We had quite an end of sprint at work and I didn't find the time to try it.

Now, I just checked the code, and well:

```js
class RequestHelper {
  static async get(service, endpoint, options = {}, { stream = false }) {
    if (stream) {
      return StreamableRequest.get(defaultRequest(service, endpoint, {
        headers: service.headers,
        qs: options,
      }));
    }
...
```

That bypasses the 'useXMLHttpRequest' flag...

I can't actually test it because I'm hitting an issue:

```
TypeError: xhr.open is not a function
    at _createXHR (/.../node-gitlab-api/node_modules/xhr/index.js:180:9)
    at createXHR.(anonymous function) (/.../node-gitlab-api/node_modules/xhr/index.js:15:16)
    at internal/util.js:230:26
    at AsyncFunction.get (/.../node-gitlab-api/dist/es5/infrastructure/XMLHttpRequester.js:19:28)
    at Function.get (/.../node-gitlab-api/dist/es5/infrastructure/RequestHelper.js:58:46)
    at Branches.all (/.../node-gitlab-api/dist/es5/services/Branches.js:13:42)
```

So I'm not sure how to proceed...

**Comment by jdalrymple** [comment]
lol no worries, i was just curious if you ever got around to it. Hmm, i should probably check that flag in that logic. lemme make a couple changes.

**Comment by jdalrymple** [comment]
K made the modifications in the jobs-pipeline-endpoints branch. Decided to throw an error if the user tries to stream and use xmlHttpRequest

**Comment by yonguelink** [comment]
Alright, added the thrown error as well.

I'm not sure how to fix that build tho... :(

**Comment by jdalrymple** [comment]
You mean this error? TypeError: xhr.open is not a function. Ill look !

**Comment by yonguelink** [comment]
Nah, I mean `codeclimate` saying `Function get has a Cognitive Complexity of 6 (exceeds 5 allowed). ` 

The xhr.open is most probably unrelated and should be dealt with in a different issue/PR/whatever

**Comment by jdalrymple** [comment]
So i just made a few more changes that i think** will help.

**Comment by jdalrymple** [comment]
Bleh, I'm still missing a code climate change. I'll make it today!

**Comment by yonguelink** [comment]
lol, while I'm there I can switch it around. gimme 5min

**Comment by jdalrymple** [comment]
Just have to switch RequestHelper with getPaginated

**Comment by jdalrymple** [comment]
like the function call on line 58 should be to getPaginated and not RequstHelper.get

**Comment by yonguelink** [comment]
Hopefully this'll do :)

**Comment by jdalrymple** [comment]
Success!!

**Comment by jdalrymple** [comment]
Im going to to go ahead and merge it :)

**Pull request merged**
