### PR TITLE
first crack at some testing

### PR DESCRIPTION
**Pull request by arsdehnel**
This is by no means intended to be merged.  This was just meant to get a starting point out there and see what you think.  Added some brief words on the readme about how to fire it up for testing.  I'm using `jest` to run the tests which is what we use at work all the time so it's just what I'm familiar with. Otherwise this is a super basic test just proving out that it can run and hit the dockerized gitlab.

### CODE REVIEW

**Comment by jdalrymple** [comment]
This is really cool! Reading up on jest now :o

**Comment by jdalrymple** [comment]
Should device a way to preconfigure the gitlab build to already have a token available

**Comment by arsdehnel** [comment]
Yup, agreed. Wanted to make sure the rest of the approach seems good before spending too much time on it.

**Comment by jdalrymple** [comment]
The only thing I'd change is the folder structure, and maybe switching to a tap reporter because I for some reason really like tap 🤣 but besides that looks really good. Would travis ci then be responsible for spinning up the gitlab instance through docker compose  and then running the library against it.  Or would the getting the library into the container also be part of a docker compose file ?

**Comment by jdalrymple** [comment]
I added more tests to the gitlabci branch! :smile:

**Comment by jdalrymple** [comment]
Weird, tried to merge my changes into your remote branch and that autoclosed the PR. hmmm

**Pull request merged**
